<?php

namespace Dh\SettingsBundle\Repository;

/**
 * CrawlersettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlersettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
