<?php

namespace Dh\SettingsBundle\Repository;

/**
 * CrawlerdataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlerdataRepository extends \Doctrine\ORM\EntityRepository
{
}
