<?php

namespace Dh\MainBundle\Repository;

/**
 * FlickrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlickrRepository extends \Doctrine\ORM\EntityRepository
{
}
