<?php

namespace Dh\MainBundle\Repository;

/**
 * RssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RssRepository extends \Doctrine\ORM\EntityRepository
{
}
